### ISSUE TITLE
The x label of figure Choosing the likelihood

### ISSUE THREAD

**Issue by findmyway** [aloctavodia/BAP#2]
I think the x label of figure *Choosing the likelihood* should be y. Since here the theta is fixed in each subplot and we are calculating the conditional probability of y observations under theta.

**Comment by aloctavodia** [comment]
Thanks for reporting this issue. I think the label is correct in the book. Maybe we can think of this notation as redundant, but I will prefer to stick to it. Others like Kruschke (Doing Bayesian Data Analysis) follows the same notation.

**Comment by findmyway** [comment]
I get it.

By the way,  I really appreciate your efforts in introducing Bayesian Analysis to people who have only little background in statistics. Recently I'm preparing to translate this book into Chinese and the authorization details are in progress. I'm wondering if I could get your help during translation through email~;)

**Comment by aloctavodia** [comment]
Good to hear BAP is going to be translated to chinese. Of course I will try
to help you. And I think you can help me to spot mistakes in the English
version.

 Some of the code examples need to be updated, because the PyMC3 syntax
changed or because new features have been added to PyMC3 like kernels for
Gaussian Process. I can help you with this too.
