### ISSUE TITLE
Softmax Regression, results are very different

### ISSUE THREAD

**Issue by ricardoV94** [aloctavodia/BAP#48]
Hello,

I was interested in the Softmax Regression example that you describe in Chapter 4 of your book, and I tried to rerun the code. In general I am getting much lower accuracy (30% for the non-identifiable model, and 20% for the identifiable one). Any idea what the problem might be?

[Google Colab Notebook](https://colab.research.google.com/drive/1YRsNMiV_TWJ2GXQxzgdiPq1TLqTCPvlf)

Thank you for your great work!

**Comment by aloctavodia** [comment]
Hi, sorry for the late response. This is really puzzling to me, I am not able to replicate your problem. You are getting lower accuracy because the inference is completely wrong, notice how all your posterior marginals are centred around zero.  Instead you should be seeing something like this 
![index](https://user-images.githubusercontent.com/1338958/64529517-74c43100-d2e1-11e9-8688-053101eac2e3.png)

You are also getting complaints from NUTS (_The chain reached the maximum tree depth. Increase max_treedepth, increase target_accept or reparameterize_ and _The number of effective samples is smaller than 25% for some parameters_). Which is signalling a problem during sampling.

**Comment by ricardoV94** [comment]
Hello again, 

I was having issues on another problem relying on the soft-max ([see pymc discourse](https://discourse.pymc.io/t/softmax-regression-with-shared-coefficients-between-classes/3816/6)) and only managed to get it working when replacing the categorical function with the multinational one. When I have some time, I will check if it also fixes the issues that I was having with your example.

Thank you very much for your reply. In the meanwhile, I am enjoying your book tremendously!

**Comment by ricardoV94** [comment]
I confirmed that using the multinomial function fixes the issues with the example. You can see it in the same [Colab Notebook](https://colab.research.google.com/drive/1YRsNMiV_TWJ2GXQxzgdiPq1TLqTCPvlf).

Seems to be a problem with the Categorical distribution in the PyMC version used by Google?

**Comment by aloctavodia** [comment]
Hi @ricardoV94 thanks for your answer. That seems to be the case. I think PyMC 3.7 introduced a few change to the categorical distribution (with respect to 3.6 version), that partially break it. That ha been fixed on master and will be delivered in the next release.
