### ISSUE TITLE
 module 'arviz' has no attribute 'plot_posterior

### ISSUE THREAD

**Issue by hungyangtsai** [aloctavodia/BAP#89]
In the final section of code in Chapter 1, when executing az.plot_posterior, an error occurs: AttributeError: module 'arviz' has no attribute 'plot_posterior'. I have updated my PyMC to PyMC5, and my ArviZ version is 0.16.1. How can I resolve this issue?

**Comment by aloctavodia** [comment]
Hi, Notice that the code in the book uses PyMC 3.11. There is a folder with more up to date code, but only for the first 3 chapters https://github.com/aloctavodia/BAP/tree/master/code_5

It seems that there was an error during installation or import, otherwise, you should not be seeing that error. Did you try installing on a fresh environment?

**Comment by hungyangtsai** [comment]
Thanks, I will try your suggestion。
